### PR TITLE
Upgrading ember-string-ishtmlsafe-polyfill

### PR DESCRIPTION
**Pull request by workmanw**
👋 -- We're updating [ember-string-ishtmlsafe-polyfill](https://github.com/workmanw/ember-string-ishtmlsafe-polyfill) to be a "native polyfill". Following the pattern provided by [ember-assign-polyfill](https://github.com/shipshapecode/ember-assign-polyfill) and [ember-getowner-polyfill](https://github.com/rwjblue/ember-getowner-polyfill).

Note: This is part of an effort to get all users of the polyfill updated.. workmanw/ember-string-ishtmlsafe-polyfill#5

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
Please fix the build issues so I can merge

**Comment by workmanw** [comment]
@BryanCrotaz Oh, hmm. This didn't break any other addons I upgraded. Let me investigate.

**Comment by workmanw** [comment]
@BryanCrotaz Okay, so this would actually be failing on master with Travis. The problem was that the `.travis.yml` was configured to run `node: 0.12` which is no longer compatible with many of the ember-cli packages. If you were to run the ember-cli upgrade for this addon, it would make this change as well. See: https://github.com/ember-cli/ember-cli/releases/tag/v2.11.0

I'm happy to squash these commits, leave them as separate, or open a new PR. Please let me know what works for you.

**Comment by BryanCrotaz** [comment]
Thanks

**Comment by workmanw** [comment]
No problem!

**Comment by BryanCrotaz** [comment]
published to npm

**Pull request merged**
